### ISSUE TITLE
Internet check issue (can't ping 1.1.1.1)

### ISSUE THREAD

**Issue by yafyz** [hanatsumi/rakuyomi#21]
Not really a bug in this project just heads up for whoever else might have issues.

For whatever reason i have issues pinging 1.1.1.1 from my home network, breaking the internet check.
Pinging 1.0.0.1 works though.

**Comment by yafyz** [comment]
oops didn't realize that you can open a blank issue without a label, sorry

**Comment by hanatsumi** [comment]
It seems that issues pinging 1.1.1.1 are kinda common, at least from a quick search. I'll change it to 1.0.0.1, it should work just the same.
