### ISSUE TITLE
Open next - skip the same chapter number

### ISSUE THREAD

**Issue by lenisko** [hanatsumi/rakuyomi#40]
**Is your feature request related to a problem? Please describe.**
To avoid reading the same chapter from different groups. It's a case for a quite a few positions.

**Describe the solution you'd like**
Before opening next file, compare chapter number to previous and skip a file till it's different.

**Describe alternatives you've considered**
As a bonus, stick to the same group (which would solve cases with multi language releases as well).

PS. Great work on this extension! I was positively surprised that someone did so advanced fetcher!

**Comment by hanatsumi** [comment]
Hey @lenisko, thanks for trying rakuyomi out! I'm glad it's being useful for you.

I've implemented your suggestion on the latest release, thanks for suggesting!

**Comment by lenisko** [comment]
Big thanks! I will verify it soon :)
