### ISSUE TITLE
Something went wrong while adding sources

### ISSUE THREAD

**Issue by Vikram1807** [hanatsumi/rakuyomi#41]
**Describe the bug**
Something went wrong 
Error
![image](https://github.com/user-attachments/assets/3dc46441-7eb3-44b0-8d7d-220a1a66d0d1)

**To Reproduce**

Add sources
![image](https://github.com/user-attachments/assets/5a73bac2-0a9f-49ec-9a4c-8a8585191b19)

**Comment by Vikram1807** [comment]
That source was down

**Comment by hanatsumi** [comment]
@Vikram1807 Which source was unavailable? Even if it isn't a huge issue, the error message isn't really helpful here, and it could be improved

**Comment by Vikram1807** [comment]
The one in my screenshot when i pasted that link in browser it was 404 : not found
