### ISSUE TITLE
Download all/a given amount of unread chapters

### ISSUE THREAD

**Issue by hanatsumi** [hanatsumi/rakuyomi#48]
In the chapter listing hamburger menu, add a button to "download unread chapters", which would prompt the user to download a given amount of unread chapters or all of them.

**Comment by lenisko** [comment]
one of the best options I used in the past was "download next X chapters" during read.

eg we have no downloads, we turn this on, I open chapter 3, chapter 4 is downloaded in backround so switch to next one is fast.

not sure backround download is possible in current shape of code though :)
