### ISSUE TITLE
Unable to Search in kindle paperwhite

### ISSUE THREAD

**Issue by achutkiran** [hanatsumi/rakuyomi#54]
**Describe the bug**
Entering manga name in search box. It says searching for few minutes and shows nothing

**To Reproduce**

1. Tap 3 lines on top left
2. Tap on Search for mangas
3. Type manga name Tower of god
4. Tap on Search
5. Text says Searching for few minutes
6. Nothing happens

**Environment:**

 - Device: Kindle Paperwhite 7th Generation
 - KOReader version:v1.7.0
 - Source name (if applicable): MangaSee, MangaDex

**`crash.log` (if applicable)**

Drag and drop the `crash.log` file here to upload it.

**Comment by hanatsumi** [comment]
The MangaSee extension has some issues when used with rakuyomi, I've described the issue in more detail on #55. I suggest you to use another source at the moment.

Closing this in favor of #55

**Comment by hanatsumi** [comment]
To uninstall the MangaSee source, go to the `rakuyomi/sources` folder inside KOReader's home, and delete the `en.nepnep.aix` file; then restart KOReader/your device.
