### ISSUE TITLE
Plugin skipping chapters if wifi is off at the end of the previous one

### ISSUE THREAD

**Issue by foldae** [hanatsumi/rakuyomi#64]
**Describe the bug**

If the wifi has been turned off during the reading, when reaching the final page of the chapter and turning to the next page, the plugin attempts to download the next one, but obviously fails, displaying an error message. After turning on the wifi and turning the page again, the plugin skips the chapter it's supposed to download, flags it as already read, and downloads the next one.

For example, I finish reading chapter 1, it tries to download ch. 2, but the wifi is off. I turn on the wifi (without exiting the chapter or the plugin), tap again on the last page, and plugin downloads ch. 3 instead of 2. If I tap more times without turing on the wifi, when I finally do, it skips as many chapters as many tries I attempted.

**To Reproduce**

1. Turn off your wifi
2. Open the last downloaded chapter of a series
3. Reach the final page and tap again to begin downloading the next chapter
4. After the error message has been displayed, turn on the wifi and try again
5. You'll see that the plugin will skip the chapter it failed to download previously and will download the next one, flagging the failed one as read

**Expected behavior**

The plugin should not flag the failed chapter as read, and should try to download it again.
It could also be useful if, at the end of a chapter, the plugin could check if the wifi is off and, if it is, turn it on before attempting to download the next chapter.

**Environment:**

 - Device: Kobo Glo HD
 - KOReader version: 2024.07
 - Source name (if applicable): MangaWorld (it)

**Comment by hanatsumi** [comment]
Fixed in v1.10.1
