### ISSUE TITLE
Clara HD error decoding reponse body when managing sources

### ISSUE THREAD

**Issue by sr-mac** [hanatsumi/rakuyomi#71]
**Describe the bug**

Managing sources displays the error
![viber_image_2024-11-18_18-15-47-851](https://github.com/user-attachments/assets/74dcb912-a5b5-4217-a2f4-765acab00406)

**To Reproduce**

1. Open Rakuyomi
2. Tap on Manage Sources
3. See error

[crash.log](https://github.com/user-attachments/files/17798560/crash.log)

**Environment:**

 - Device: [e.g. Kindle Paperwhite 5]
 - KOReader version: [e.g. 2024.05]
 - Source name (if applicable): [e.g. MangaDex]

**`crash.log` (if applicable)**

Drag and drop the `crash.log` file here to upload it.

**Comment by hanatsumi** [comment]
Hmm, I can't quite reproduce this. Can you post your `settings.json`?

**Comment by sr-mac** [comment]
> Hmm, I can't quite reproduce this. Can you post your `settings.json`?

Here's mine based from some aidoku links
{
    "$schema": "https://github.com/hanatsumi/rakuyomi/releases/download/main/settings.schema.json",
    "source_lists": [
        "https://mangadex.org/index.min.json",
		"https://comick.io/index.min.json",
		"https://flamecomics.com/index.min.json"
    ],
    "languages": ["en"]
}

**Comment by hanatsumi** [comment]
Your `source_lists` configuration are invalid, if you try to access them with your browser you will encounter a "not found" error. You can get a valid source list in Aidoku's Discord.

The error message here could be improved though, I'll look into it

**Comment by sr-mac** [comment]
> Your `source_lists` configuration are invalid, if you try to access them with your browser you will encounter a "not found" error. You can get a valid source list in Aidoku's Discord.
> 
> The error message here could be improved though, I'll look into it

Thank you! I'm a bit lost in Aidoku, can you provide a hint on how can I better filter it out to find links if allowed. I'm sorry!

**Comment by hanatsumi** [comment]
A link like the following should work: https://raw.githubusercontent.com/Skittyblock/aidoku-community-sources/refs/heads/gh-pages/index.min.json

**Comment by sr-mac** [comment]
> https://raw.githubusercontent.com/Skittyblock/aidoku-community-sources/refs/heads/gh-pages/index.min.json

Thank you! I'll try it out!

**Comment by sr-mac** [comment]
Thanks to your link, its now working. I literally thought I had to add the sources individually.
