### ISSUE TITLE
Pocketbook washed out colors.

### ISSUE THREAD

**Issue by Deulfi** [hanatsumi/rakuyomi#75]
This is not an issue with rakuyomi, but with Koreader and more specifically with Pocketbook. I just leave this information here, maybe this can be added as a note in the README.

I noticed that sometimes the colors looked washed out, on my pocketbook verse pro color. This is apparently not something new and to resolve this issue I had to **enable dithering** in the Koreader settings.

Some issues in the Koreader repo about this:
https://github.com/koreader/koreader/issues/10446
https://github.com/koreader/koreader/issues/12488

**Comment by sr-mac** [comment]
You can crank up the contrast in koreader for this. set 1 to 1.5 or 2 for vivid outcome. Sometimes the color is just too light on the manga itself. Hope it helps.

**Comment by hanatsumi** [comment]
Right now we don't really change any settings of KOReader's file reader, but it might be a good idea to eventually "force enable" some settings while reading manga (like dithering, or auto-cropping)

For now, I'll look into documenting some recommended settings.

**Comment by hanatsumi** [comment]
I've created #81 as a sort of follow-up issue of this
