### ISSUE TITLE
Rakuyomi entry not appearing in Search on Kindle PW2

### ISSUE THREAD

**Issue by batibat** [hanatsumi/rakuyomi#79]
I can't find Rakuyomi in the options under Search on Koreader after installing the plugin on a Kindle Paperwhite 2.

**To Reproduce**

1. Download Rakuyomi Kindle release [1.11.1]
2. Place the rakuyomi.koplugin folder inside KOReader's plugins folder
3. Make settings.json with source list from Aidoku based on instructions, then paste into /koreader/rakuyomi/ 
4. Eject and run Koreader
5. Open a book in Koreader
6. Go to Search menu to find Rakuyomi entry. No "Rakuyomi" entry found

**Expected behavior**

Rakuyomi should be found in the Search entries.

**Environment:**

 - Device: Kindle Paperwhite 2
 - KOReader version: v2024.11

**`crash.log` (if applicable)**

---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 11/22/24-06:49:46
has monolibtic? no (libs/libkoreader-monolibtic.so: cannot open shared object file: No such file or directory)
lib_search_path: libs/?
lib_basic_format: lib%s.so
lib_version_format: lib%s.so.%s
 [*] Version: v2024.11

ffi.load: rt.so.1 (RTLD_GLOBAL)
ffi.findlib: utf8proc [3]
ffi.load: libs/libutf8proc.so.3
ffi.findlib: blitbuffer
ffi.load: libs/libblitbuffer.so
ffi.findlib: fbink_input [1]
ffi.load: libs/libfbink_input.so.1
[FBInk] /dev/input/event0: `max77696-onkey` = KEY | POWER_BUTTON
[FBInk] /dev/input/event1: `cyttsp4_mt` = TOUCHSCREEN
[ko-input] Forked off fake event generator (pid: 9256)
11/22/24-06:49:47 INFO  initializing for device KindlePaperWhite2 
11/22/24-06:49:47 INFO  framebuffer resolution: {
  h = 1024,
  w = 758
} --[[table: 0x404be278]] 
ffi.findlib: wrap-mupdf
ffi.load: libs/libwrap-mupdf.so
ffi.findlib: sqlite3 [0]
ffi.load: libs/libsqlite3.so.0
ffi.findlib: freetype [6]
ffi.load: libs/libfreetype.so.6
ffi.findlib: harfbuzz [0]
ffi.load: libs/libharfbuzz.so.0
ffi.findlib: zstd [1]
ffi.load: libs/libzstd.so.1
11/22/24-06:49:48 INFO  Loading plugins from directory: plugins 
11/22/24-06:49:49 INFO  setting up __gc proxy 
11/22/24-06:49:50 INFO  Loading Rakuyomi plugin... 
11/22/24-06:49:50 INFO  Spawned HTTP server with PID 9262 
11/22/24-06:49:50 INFO  Requesting to /health-check 
[2m2024-11-21T22:49:50.998208Z[0m [31mERROR[0m [2muds_http_request[0m[2m:[0m error while performing request: client error (Connect)

Caused by:
    Connection refused (os error 111)    
[2m2024-11-21T22:49:51.032568Z[0m [32m INFO[0m [2mserver[0m[2m:[0m starting rakuyomi, version: v1.11.1    
11/22/24-06:49:52 INFO  Requesting to /health-check
11/22/24-06:50:08 INFO  opening file /mnt/us/documents/The Hating Game - Sally Thorne.epub 
CRE: font NotoSerifKR regular: updated weight from 500 to 400
CRE: font NotoSerifKR bold: updated weight from 900 to 700
CRE: font PMN Caecilia LT regular: updated weight from 500 to 400
CRE: font NotoSansKR bold: updated weight from 900 to 700
11/22/24-06:50:09 INFO  Inhibiting user input 
11/22/24-06:50:13 INFO  Restoring user input handling 
11/22/24-06:50:22 INFO  opening file /mnt/us/documents/The Hating Game - Sally Thorne.epub 
11/22/24-06:50:22 INFO  Inhibiting user input 
11/22/24-06:50:23 INFO  Restoring user input handling 
11/22/24-06:50:57 INFO  opening file /mnt/us/koreader/crash.log 
11/22/24-06:50:57 INFO  Inhibiting user input 
11/22/24-06:50:59 INFO  Restoring user input handling 
11/22/24-06:51:37 INFO  UIManager: No dialogs left to show 
11/22/24-06:51:37 INFO  Tearing down UIManager with exit code: 0 
[ko-input] Closed input device with fd: 11 @ idx: 1 (matched by idx)
[ko-input] Closed input device with fd: 10 @ idx: 0 (matched by idx)
lipc-wait-event exited normally with status: 0
11/22/24-06:51:37 INFO  Terminating subprocess with PID 9262 
11/22/24-06:51:37 INFO  Subprocess is done: true

**Comment by hanatsumi** [comment]
Hmm, there doesn't seem to be anything wrong from the logs, even the error messages are quite expected. Can you attach a print of the search menu?

I've updated my PW5 to KOReader v2024.11 to check if there was some kind of breakage but things seem to be working fine, the only difference is that the menu item is on a separate page.

**Comment by batibat** [comment]
![20241122_092302](https://github.com/user-attachments/assets/120b2359-23fe-4f28-b9d7-0b7215846d48)
![20241122_092240](https://github.com/user-attachments/assets/8be8daee-4c95-46c7-981d-f627d762f69a)

Here's what it looks like under the Search menu. 

I also checked under Tools > More tools > Plugin Management to see if maybe Rakuyomi isn't activated, but there's a checkmark beside it.

**Comment by hanatsumi** [comment]
@batibat You need to be on the file manager view in order for the menu item to appear, it won't show up from inside the reader

**Comment by batibat** [comment]
Found it! Have installed sources and dlled some sample chapters successfully. Glad it was just me being slow and not an actual issue. Sorry about that. Thanks for your prompt response!

**Comment by hanatsumi** [comment]
No problem! I'll make a small change to the usage instructions to clarify that one needs to be in the file manager, as it wasn't really specified anywhere
