### ISSUE TITLE
Pockectbook Era Color Error: "Deadline has elapsed"

### ISSUE THREAD

**Issue by AProgrammerPolarBear** [hanatsumi/rakuyomi#83]
**Describe the bug**

Error occurs everytime I searched for Manga. KOReader Wifi settings is already forced as:

Action when WiFi is off: Turn on
Action when done with WiFi: Leave on

**To Reproduce**

1. Go to 'Search for mangas'
2. Type the manga name, i.e 'spy x family'
3. Wait to fetch data/finish searching
4. Screen will be redirected to KOReader homescreen
5. Error will be shown

**Expected behavior**

Manga titles will be shown 

**Environment:**

 - Device: Pocketbook Era Color PB700K3
 - KOReader version: 202407000269
 - Source name: Bato.to, ComicK, MangaDex

**`crash.log` (if applicable)**
[crash.log](https://github.com/user-attachments/files/17892759/crash.log)

**Comment by hanatsumi** [comment]
From the logs, I can see that the MangaSee source was installed. It is known to cause some issues like the ones you've experienced, see #55. Closing as a duplicate for now, please reopen if the error persists after uninstalling the MangaSee source (you can uninstall them by tap-and-holding over their name on the "installed sources" dialog)
