### ISSUE TITLE
Unable to open and add manga to the library from search

### ISSUE THREAD

**Issue by teddy74eva** [hanatsumi/rakuyomi#87]
**Describe the bug**

When searching for a manga, neither tapping nor holding the search results does anything. The 3 dots button does nothing as well. However, manga already added to the library can be opened, downloaded etc. just fine.

**To Reproduce**

1. Search for a manga
2. Tap or hold on an entry from the list
3. Nothing happens

**Expected behavior**

Chapters appearing after a tap or an option to add to library appearing after a hold or a tap of the 3 dots button.

**Environment:**

 - Device: PocketBook InkPad 3 Pro
 - KOReader version: 2024.07, 2024.11
 - Source name (if applicable): MangaDex, MangaNato, MangaFox

**`crash.log` (if applicable)**

I'll attach later as I'm on mobile right now but I had a quick look on the reader itself and nothing stands out, there are no errors produced.

**Comment by teddy74eva** [comment]
The above concerns 1.11.2, quickly gave 1.11.1 a go and it works as expected.

**Comment by hanatsumi** [comment]
Should be fixed in 1.11.3 (thanks to @Saizan!)

**Comment by teddy74eva** [comment]
Can confirm, works as expected in 1.11.3, thanks!
